/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea2StevenVargasB78013EyleenQuirosB76084;

import file.VehicleFile;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eyleen
 * @author Steven
 */
public class List extends javax.swing.JInternalFrame {

    VehicleFile vehicleFile;

    public List() {
        try {

            this.vehicleFile = new VehicleFile(new File("./Vehicle.dat"));
        } catch (IOException ex) {

        }
        this.setTitle("List of vehicles");
        initComponents();
    }

    /**
     * Creates new form List
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listVeicles = new javax.swing.JTextArea();
        update = new javax.swing.JButton();

        setClosable(true);

        listVeicles.setEditable(false);
        listVeicles.setColumns(20);
        listVeicles.setRows(5);
        jScrollPane1.setViewportView(listVeicles);

        update.setText("Actualizar");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        listVeicles.setText("");
        Object[] list;
        //Este try imprime la lista de vehículos
        try {
            list = vehicleFile.getAllVehicles().toArray();
            for (int i = 0; i < list.length; i++) {
                this.listVeicles.setText(this.listVeicles.getText() + list[i].toString() + "\n");
            }
        } catch (IOException ex) {
            Logger.getLogger(List.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listVeicles;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
